version: '2'

services:
   db:
     image: mariadb:10
     ports:
      - 3307:3307
     restart: always
     volumes:
       - /var/cloucapstone/mysql:/var/lib/mysql
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD=true \
       MYSQL_DATABASE=cloudcasptone \
       MYSQL_USER=admin \
       MYSQL_PASSWORD=GL7BQZbR5CLEux
     stdin_open: true
     tty: true  

